### PR TITLE
please for fucks sake dont include a module with one command

### PR DESCRIPTION
**Pull request by That-One-Nerd**
please dont

### CODE REVIEW

**Comment by n-Ultima** [comment]
Does this give any performance boosts? Why make a "text" module? Every command involves text.

**Comment by That-One-Nerd** [comment]
It doesn't give any preformance boosts, but it doesnt remove any speed either. I made a text module, because yes, every command invoves text, but this one is entirely reliant on it. It involves the snipe and purge commands, because they affect only text.

**Comment by That-One-Nerd** [comment]
Also, what's the point of having a module entirely based off of a single command. That's the whole reason I made the pull request

**Comment by That-One-Nerd** [comment]
close if gay

**Comment by That-One-Nerd** [comment]
why would you do this

**Pull request closed without merging**
